//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KasifBusiness.DB_Operations.EntityObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLGE_INFO
    {
        public long GUID { get; set; }
        public short STATUS { get; set; }
        public Nullable<long> LASTUPDATED { get; set; }
        public string BOLGE_ADI { get; set; }
        public string BOLGE_ILCE { get; set; }
    }
}
