//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KasifBusiness.DB_Operations.EntityObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DERS_KONU_BILGI
    {
        public long GUID { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<long> LASTUPDATED { get; set; }
        public Nullable<long> DERS_ID { get; set; }
        public string KONU { get; set; }
    }
}
