//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KasifBusiness.DB_Operations.EntityObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_TREE
    {
        public long GUID { get; set; }
        public short STATUS { get; set; }
        public long LASTUPDATED { get; set; }
        public Nullable<long> PARENT_NODE_GUID { get; set; }
        public string NODE_TYPE { get; set; }
        public string NODE_DISPLAY_NAME { get; set; }
        public Nullable<short> NODE_POSITION { get; set; }
        public string CLASS_NAME { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<int> RESOURCE_ID { get; set; }
    }
}
