//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KasifBusiness.DB_Operations.EntityObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_TILES
    {
        public long GUID { get; set; }
        public short STATUS { get; set; }
        public Nullable<long> LASTUPDATED { get; set; }
        public string STYLE { get; set; }
        public Nullable<long> NODE_GUID { get; set; }
        public string DISPLAY_NAME { get; set; }
        public Nullable<int> NODE_POSITION { get; set; }
        public string FILE_NAME { get; set; }
        public string ICON_NAME { get; set; }
        public string TILE_TYPE { get; set; }
    }
}
