//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KasifBusiness.DB_Operations.EntityObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGR_BILGI
    {
        public long GUID { get; set; }
        public short STATUS { get; set; }
        public Nullable<long> LASTUPDATED { get; set; }
        public Nullable<int> OGR_ID { get; set; }
        public Nullable<int> OGR_NO { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public Nullable<short> CLASS { get; set; }
        public string SUBCLASS { get; set; }
        public string SCHOOL_NAME { get; set; }
        public string DISTRICT { get; set; }
        public string PARENT_NAME { get; set; }
        public string DATE_OF_BIRTH { get; set; }
        public string BIRT_PLACE { get; set; }
        public string PHONE { get; set; }
        public string PARENT_PHONE { get; set; }
        public string OGR_EMAIL { get; set; }
        public string PARENT_EMAIL { get; set; }
        public byte[] OGR_IMG { get; set; }
    }
}
