//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KasifBusiness.DB_Operations.EntityObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGR_TEST_REL
    {
        public long GUID { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<long> LASTUPDATED { get; set; }
        public Nullable<long> TEST_ID { get; set; }
        public Nullable<long> OGR_ID { get; set; }
        public Nullable<short> DURUM { get; set; }
        public Nullable<int> DOGRU_SAYISI { get; set; }
        public Nullable<int> YANLIS_SAYISI { get; set; }
    }
}
