//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KasifBusiness.DB_Operations.EntityObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_USER
    {
        public long GUID { get; set; }
        public short STATUS { get; set; }
        public long LASTUPDATED { get; set; }
        public string USER_ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string EMAIL { get; set; }
        public Nullable<short> IS_ADMIN { get; set; }
        public Nullable<long> INSERT_USER { get; set; }
        public Nullable<long> INSERT_DATETIME { get; set; }
        public Nullable<long> LAST_LOGIN_DATE { get; set; }
        public Nullable<long> LAST_PWD_CHANGE_DATE { get; set; }
        public Nullable<short> USER_STATUS { get; set; }
        public byte[] PASSWORD { get; set; }
        public Nullable<short> SINIF { get; set; }
        public Nullable<long> BOLGE_ID { get; set; }
    }
}
