//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KasifBusiness.DB_Operations.EntityObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SESSION_INFO
    {
        public string USER_ID { get; set; }
        public long LOGIN_DATETIME { get; set; }
        public Nullable<int> SUCCESS { get; set; }
        public string FAILURE_REASON { get; set; }
        public Nullable<int> INCORRECT_PWD_COUNT { get; set; }
        public long SESSION_GUID { get; set; }
    }
}
